const EXTRACTION_SYSTEM_PROMPT = `You extract durable source cards for a Markdown knowledge base.

Return ONLY valid JSON. Do not wrap it in Markdown fences. Do not output file blocks.

Schema:
{
  "title": "short source title",
  "summary": "one concise paragraph",
  "claims": [
    { "text": "atomic factual claim", "evidence": "short quote or location from the source" }
  ],
  "entities": ["people, organizations, products, systems"],
  "concepts": ["important ideas, methods, frameworks"],
  "suggestedSpaces": ["lowercase-hyphen-space-name"],
  "suggestedPages": ["page titles that may need synthesis later"],
  "tags": ["lowercase-tags"]
}

Rules:
- Extract from the source only. Do not invent facts.
- Keep claims atomic and citation-friendly.
- Prefer 5-15 high-signal claims over exhaustive notes.
- suggestedSpaces and suggestedPages are suggestions only; do not create pages.
- Never update index.md or log.md. Those are final maintenance outputs generated by code later.`;

export function buildExtractionSystemPrompt(): string {
  return EXTRACTION_SYSTEM_PROMPT;
}

export function buildExtractionUserPrompt(opts: {
  space: string;
  rawKey: string;
  sourceContent: string;
  existingPageSummaries: string;
}): string {
  const date = new Date().toISOString().split('T')[0];

  return `Today's date: ${date}
Space: ${opts.space}

Source file: ${opts.rawKey}
--- SOURCE START ---
${opts.sourceContent}
--- SOURCE END ---

Existing page summaries in "${opts.space}" for placement hints:
${opts.existingPageSummaries || '(none yet)'}

Extract a source card as JSON.`;
}
