'use client';

import { useState } from 'react';
import { ICONS } from '@/lib/icons';
import { RenderedMarkdown } from '@/lib/markdown-preview';
import type { Doc } from '@/lib/types';

type EditorProps = {
  doc?: Doc;
  docId?: string;
  etag?: string;
  onClose: () => void;
  onSave: (title: string, docId?: string) => void;
  showToast: (msg: string) => void;
};

function buildInitialBody(doc?: Doc): string {
  if (doc?.generated) {
    return `# ${doc.title}\n\n> _Originally generated by Ask the wiki on ${doc.updated}._\n\n## Question\n\n${doc.question || ''}\n\n## Answer\n\n${typeof doc.answer === 'string' ? doc.answer : ''}\n\n## Sources\n\n${(doc.cites || []).map((c, i) => `${i + 1}. **${c.title}** — _${c.section}_`).join('\n')}\n\n## My notes\n\n_Add your own notes here…_\n`;
  }
  if (doc && 'kind' in doc && doc.kind === 'live' && doc.raw_markdown) {
    return doc.raw_markdown;
  }
  return `# ${doc?.title || 'Untitled'}\n\nStart writing your notes here.\n\n## Section\n\n- bullet\n- bullet\n`;
}

export function Editor({ doc, docId, etag, onClose, onSave, showToast }: EditorProps) {
  const [title, setTitle] = useState(doc?.title || 'Untitled');
  const [body, setBody] = useState(() => buildInitialBody(doc));
  const [saving, setSaving] = useState(false);

  const handleSave = async () => {
    if (saving) return;
    setSaving(true);

    try {
      if (docId && !docId.startsWith('__')) {
        // Update existing doc — server syncs title into frontmatter
        const res = await fetch(`/api/docs/${encodeURIComponent(docId)}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ body, title, etag }),
        });

        if (res.status === 409) {
          showToast('This page was edited elsewhere. Reloading latest version.');
          onClose();
          return;
        }
        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          showToast(data.detail || 'Failed to save');
          return;
        }
        onSave(title, docId);
      } else {
        // Create new doc
        const res = await fetch('/api/docs', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ title, body }),
        });

        if (!res.ok) {
          // Surface the server's `detail` (e.g. 'A page with slug "foo"
          // already exists') so the user knows why creation failed.
          const data = await res.json().catch(() => ({}));
          showToast(data.detail || 'Failed to create page');
          return;
        }
        const data = await res.json();
        onSave(title, data.id);
      }
    } catch {
      showToast('Network error — could not save');
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <div className="doc-toolbar">
        <div className="crumbs">
          <span className="crumb">My wiki</span>
          <span className="sep">/</span>
          <span className="crumb current">{title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md</span>
        </div>
        <span className="tag-chip personal">{ICONS.lock} private · draft</span>
        <button className="btn ghost" onClick={onClose}>Cancel</button>
        <button className="btn primary" onClick={handleSave} disabled={saving}>
          {ICONS.check} {saving ? 'Saving…' : 'Save'}
        </button>
      </div>
      <div className="editor-wrap" style={{ flex: 1, minHeight: 0 }}>
        <div className="editor">
          <input className="editor-title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Untitled"/>
          <textarea className="editor-input" value={body}
                    onChange={(e) => setBody(e.target.value)}
                    spellCheck={false}/>
        </div>
        <div className="preview">
          <div style={{ color: 'var(--fg-3)', fontSize: 10.5, fontWeight: 600, letterSpacing: '.06em', textTransform: 'uppercase', marginBottom: 14 }}>Preview</div>
          <article className="doc">
            <RenderedMarkdown title={title} body={body}/>
          </article>
        </div>
      </div>
    </>
  );
}
