'use client';

import { useState } from 'react';
import { ICONS } from '@/lib/icons';
import { RenderedMarkdown } from '@/lib/markdown-preview';
import type { Doc } from '@/lib/mock/data';

type EditorProps = {
  doc?: Doc;
  onClose: () => void;
  onSave: (title: string, body: string) => void;
};

function buildInitialBody(doc?: Doc): string {
  if (doc?.generated) {
    return `# ${doc.title}\n\n> _Originally generated by Ask the wiki on ${doc.updated}._\n\n## Question\n\n${doc.question || ''}\n\n## Answer\n\n${typeof doc.answer === 'string' ? doc.answer : ''}\n\n## Sources\n\n${(doc.cites || []).map((c, i) => `${i + 1}. **${c.title}** — _${c.section}_`).join('\n')}\n\n## My notes\n\n_Add your own notes here…_\n`;
  }
  return `# ${doc?.title || 'Untitled'}\n\nStart writing your notes here. This page is **private** by default — only you can see it until you move it to a shared space.\n\n## Section\n\n- bullet\n- bullet\n- bullet\n\n\`\`\`bash\n# Some code\necho "hello"\n\`\`\`\n`;
}

export function Editor({ doc, onClose, onSave }: EditorProps) {
  const [title, setTitle] = useState(doc?.title || 'Untitled');
  const [body, setBody] = useState(() => buildInitialBody(doc));
  return (
    <>
      <div className="doc-toolbar">
        <div className="crumbs">
          <span className="crumb">personal</span>
          <span className="sep">/</span>
          <span className="crumb">notes</span>
          <span className="sep">/</span>
          <span className="crumb current">{title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md</span>
        </div>
        <span className="tag-chip personal">{ICONS.lock} private · draft</span>
        <span style={{ color: 'var(--fg-3)', fontSize: 11.5, fontFamily: 'var(--font-mono)' }}>autosaved 2s ago</span>
        <button className="btn ghost" onClick={onClose}>Cancel</button>
        <button className="btn primary" onClick={() => onSave(title, body)}>{ICONS.check} Save</button>
      </div>
      <div className="editor-wrap" style={{ flex: 1, minHeight: 0 }}>
        <div className="editor">
          <input className="editor-title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Untitled"/>
          <div style={{ color: 'var(--fg-3)', fontSize: 11, fontFamily: 'var(--font-mono)', marginBottom: 18 }}>
            s3://wikillm/tenants/acme/users/u-1042/wiki/notes/{title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md
          </div>
          <textarea className="editor-input" value={body}
                    onChange={(e) => setBody(e.target.value)}
                    spellCheck={false}/>
        </div>
        <div className="preview">
          <div style={{ color: 'var(--fg-3)', fontSize: 10.5, fontWeight: 600, letterSpacing: '.06em', textTransform: 'uppercase', marginBottom: 14 }}>Preview</div>
          <article className="doc">
            <RenderedMarkdown title={title} body={body}/>
          </article>
        </div>
      </div>
    </>
  );
}
