import { Fragment } from 'react';
import { ICONS } from '@/lib/icons';
import type { GeneratedDoc } from '@/lib/types';

type GeneratedDocReaderProps = {
  doc: GeneratedDoc;
  onEdit: () => void;
};

export function GeneratedDocReader({ doc, onEdit }: GeneratedDocReaderProps) {
  return <>
    <div className="doc-toolbar">
      <div className="crumbs">
        {doc.path.split(' / ').map((p, i, a) => (
          <Fragment key={i}>
            <span className={'crumb' + (i === a.length - 1 ? ' current' : '')}>{p}</span>
            {i < a.length - 1 && <span className="sep">/</span>}
          </Fragment>
        ))}
      </div>
      <span className="tag-chip personal">{ICONS.lock} private</span>
      <span className="tag-chip generated">{ICONS.spark} generated</span>
      <button className="btn ghost icon-only" title="Star">{ICONS.star}</button>
      <button className="btn" onClick={onEdit}>{ICONS.edit} Edit</button>
      <button className="btn">{ICONS.share} Share</button>
    </div>
    <div className="doc-wrap">
      <article className="doc">
        <div className="gen-hero">
          <div className="gen-hero-eyebrow">
            <span className="gen-hero-icon">{ICONS.spark}</span>
            <span>Generated by Ask the wiki</span>
            <span style={{ width: 3, height: 3, borderRadius: '50%', background: 'var(--fg-3)', display: 'inline-block' }}></span>
            <span>{doc.updated}</span>
            <span style={{ width: 3, height: 3, borderRadius: '50%', background: 'var(--fg-3)', display: 'inline-block' }}></span>
            <span>{doc.cites?.length || 0} source{(doc.cites?.length || 0) === 1 ? '' : 's'}</span>
          </div>
          <h1 className="gen-hero-q">{doc.question}</h1>
        </div>

        <div className="gen-section">
          <div className="gen-section-label">Answer</div>
          <div className="gen-answer">{doc.answer}</div>
        </div>

        {doc.cites && doc.cites.length > 0 && (
          <div className="gen-section">
            <div className="gen-section-label">Sources</div>
            <div className="gen-sources">
              {doc.cites.map((c, i) => (
                <div key={i} className="gen-source">
                  <span className="gen-source-num">{i + 1}</span>
                  <div style={{ flex: 1 }}>
                    <div className="gen-source-title">{c.title}</div>
                    <div className="gen-source-section">{c.section}</div>
                  </div>
                  <span style={{ color: 'var(--fg-3)' }}>{ICONS.arrow}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="gen-section">
          <div className="gen-section-label">Notes</div>
          <p style={{ color: 'var(--fg-2)', fontStyle: 'italic', margin: '4px 0 8px' }}>Add your own notes — they stay private to you.</p>
          <div className="gen-notes-placeholder">Click to add a note…</div>
        </div>

        <div className="callout info" style={{ marginTop: 24 }}>
          <span className="icon">{ICONS.info}</span>
          <div>This page was generated from a chat answer. The original sources are linked above. If a source changes, this page <strong>does not</strong> update automatically — re-run the question to refresh.</div>
        </div>
      </article>
      <aside className="toc">
        <div className="toc-title">Page</div>
        <a href="#" className="active">Answer</a>
        <a href="#">Sources</a>
        <a href="#">Notes</a>
        <div style={{ marginTop: 18, paddingTop: 12, borderTop: '1px solid var(--line)', fontSize: 11, color: 'var(--fg-3)', fontFamily: 'var(--font-mono)', lineHeight: 1.6 }}>
          <div>type <span style={{ color: 'var(--fg-2)' }}>generated</span></div>
          <div>updated <span style={{ color: 'var(--fg-2)' }}>{doc.updated}</span></div>
          <div>visibility <span style={{ color: 'var(--fg-2)' }}>private</span></div>
          <div style={{ marginTop: 4 }}>{doc.checksum}</div>
        </div>
      </aside>
    </div>
  </>;
}
